version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: referral_db
      POSTGRES_USER: referral_user
      POSTGRES_PASSWORD: referral_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U referral_user -d referral_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: >
      sh -c "sleep 10 && 
      python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://referral_user:referral_pass@db:5432/referral_db
      - DEBUG=True
    restart: unless-stopped

volumes:
  postgres_data: